---
driver:
  name: docker

platforms:
  - name: almalinux-9
    image: almalinux:9
    pre_build_image: true
    command: bash -c "exec sleep infinity"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rshared
    cgroupns_mode: host
    env:
      container: docker

  - name: ubuntu-22.04
    image: ubuntu:22.04
    pre_build_image: true
    command: bash -c "apt-get update && apt-get install -y curl && exec sleep infinity"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rshared
    cgroupns_mode: host
    env:
      container: docker
      DEBIAN_FRONTEND: noninteractive

  - name: debian-12
    image: debian:12
    pre_build_image: true
    command: bash -c "apt-get update && apt-get install -y curl && exec sleep infinity"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rshared
    cgroupns_mode: host
    env:
      container: docker
      DEBIAN_FRONTEND: noninteractive

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars: {}
    group_vars: {}

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
